
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    server {
        listen       80; # Port
        server_name  localhost;

        # 1. Konfigurasi Frontend (React Build)
        location / {
            root   "../client/dist"; # Sesuaikan dengan lokasi folder dist kamu
            index  index.html index.htm;
            try_files $uri $uri/ /index.html; # Penting agar React Router tidak error saat di-refresh
        }

        # 2. Konfigurasi Proxy ke Backend (Node.js + Socket.IO)
        location /api/ {
            proxy_pass http://localhost:3000; # Sesuaikan dengan PORT server Node.js kamu
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # 3. Konfigurasi Khusus Socket.IO
        location /socket.io/ {
            proxy_pass http://localhost:3000; # Port backend
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }

    #gzip  on;
	
    # include "D:/laragon/etc/nginx/php_upstream.conf";
    # include "D:/laragon/etc/nginx/sites-enabled/*.conf";
    client_max_body_size 2000M;
	server_names_hash_bucket_size 64;
}
